from utils import Box
    

ZEBRA_CROSSING = Box(
    top_left=(173, 202),
    bottom_right=(644, 232),
)

ZEBRA_THRESHOLD = 900

DETECT_BOX_OFFSET_TL = (0, 0) #(-50, -50)
DETECT_BOX_BR = ()

LINE_THICKNESS = 2
VEHICLE_DET_THRESHOLD = 0.6
TRAFFIC_LIGHT_THRESHOLD = 0.4